web:
  restart: always
  build: .
  ports:
    - "5000:5000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
  environment:
    - DB_NAME=postgres
    - DB_PASS=postgres
    - DB_PORT=5432
    - DB_SERVICE=postgres
    - DB_USER=postgres
    - DEBUG=False
    - SECRET_KEY=keykeykey

nginx:
  restart: always
  build: .
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
