version: '2'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/www/static/app
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
