version: '3.6'
services:
  web:
    image: python:2.7-alpine
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - ./web:/web
      - /usr/src/app/static
    restart: always
    links:
      - mongo-db:mongo-db
    #command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/www/static
    links:
      - web:web

  mongo-db:
    restart: always
    image: mongo:3.6.3-jessie
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
