nginx:
  restart: always
  image: 'tutum/nginx:latest'
  links:
    - eng-web
  ports:
    - '80:80'
    - '443'
  volumes_from:
    - eng-web

eng-web:
  image: 'ferrarojespn/eng-web2:latest'
  ports:
      - "5000:5000"
  links:
      - postgres:postgres
  environment:
    - DB_NAME=postgres
    - DB_PASS=postgres
    - DB_PORT=5432
    - DB_SERVICE=postgres
    - DB_USER=postgres
    - DEBUG=False
    - SECRET_KEY=keykeykey
data:
  image: postgres:latest

postgres:
  restart: always
  image: postgres:latest
  volumes:
    - data
  ports:
    - "5432:5432"
