web:
  restart: always
  image: ferraro/flask-app:web-prod
  build: .
  ports:
    - "5000:5000"
  links:
    - postgres:postgres
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app
