web-dev:
  restart: always
  build: .
  ports:
    - "4000:4000"
  volumes:
    - /usr/src/app
    # - /AsRunDrop/GenerateReport:/folderRNN
    # - /dropXML:/dropXML
    # - /wordpress:/wordpress
    - /wordpress
    - /dropXML
    - /folderRNN
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :4000 app:app
#   links:
#     - "postgres:postgres"
#
# data:
#   image: postgres:latest
#   volumes:
#     - /var/lib/postgresql
#   command: "true"
#
# postgres:
#   restart: always
#   image: postgres:latest
#   volumes_from:
#     - data
#   ports:
#     - "5432:5432"
