web:
  restart: always
  build: ./web
  ports:
    - 5000:5000
  links:
    - mongo-db:mongo-db
  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

data:
  image: mongo:3.6.3-jessie
  command: "true"

mongo-db:
  image: mongo:3.6.3-jessie
  container_name: "mongodb"
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
  ports:
      - 27017:27017
  restart: always
  volumes_from:
    - data
