eng-web:
  build: .
  ports:
      - "5000:5000"
  environment:
    - DB_NAME=postgres
    - DB_PASS=postgres
    - DB_PORT=5432
    - DB_SERVICE=postgres
    - DB_USER=postgres
    - DEBUG=False
    - SECRET_KEY=keykeykey
