nginx:
  restart: always
  build: .
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

web:
  restart: always
  image: ferraro/flask-app:latest
  expose:
    - "5000"
