version: '2'
services:
  web:
    image: ferraro/flask-app:rnn
    ports:
      - "5000:5000"
    links:
      - postgres:postgres
    volumes:
      - /usr/src/app/static
    env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app

  nginx:
    restart: always
    image: tutum/nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - web
    links:
      - web:web

  data:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
