version: '3.6'
services:
  web:
    image: python:2.7-alpine
    restart: always
    build: ./web
    ports:
      - 5000:5000
    links:
      - mongo-db:mongo-db
    volumes:
      - /usr/src/app/static
    #env_file: .env
    command: /usr/local/bin/gunicorn -w 2 -b :5000 app:app

  mongo-db:
    restart: always
    image: mongo:3.6.3-jessie
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    volumes:
      - data:/data/db
volumes:
  data:
