version: '3.6'
services:
  web:
    build: .
    ports:
        - "5000:5000"
    volumes:
        - .:/app

#   mongo-db:
#     restart: always
#     image: mongo:3.6.3-jessie
#     container_name: "mongodb"
#     environment:
#       - MONGO_DATA_DIR=/data/db
#       - MONGO_LOG_DIR=/dev/null
#     ports:
#         - 27017:27017
#     links:
#         - mongo-seed
# volumes:
#   mongo-seed:
#   build: ./data
#   links:
#     - mongodb
